// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package database

import (
	"time"

	"github.com/google/uuid"
)

type Creditrequest struct {
	ID          uuid.UUID
	PersonID    uuid.UUID
	StartAmount float64
	Amount      float64
	Status      string
	Reason      string
	Note        string
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

type Person struct {
	ID        uuid.UUID
	Fname     string
	Lname     string
	Age       int32
	Email     string
	Job       string
	Savings   float64
	Due       float64
	CreatedAt time.Time
	UpdatedAt time.Time
}
